--INSERT INTO student (rollno, name, marks)  VALUES
--                                          (1, 'Aarav Kumar', 85),
--                                          (2, 'Ananya Gupta', 92),
--                                          (3, 'Arjun Singh', 78),
--                                          (4, 'Ishita Sharma', 65),
--                                          (5, 'Rahul Verma', 89);